name: CI/CD Elixir
on:
  push:
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    name: Compile
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Elixir
        uses: erlef/setup-beam@v1.20.4
        with:
          version-file: .tool-versions
          version-type: strict
      - name: Cache deps directory
        if: steps.cache-deps.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        id: cache-deps
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock')}}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Get dependencies
        run: mix deps.get
      - run: mix compile --warnings-as-errors
      - name: Run tests
        run: mix test --max-failures 1 --trace --warnings-as-errors
      - name: Check code is formatted
        run: mix format --check-formatted
